spring:
  datasource:
    url: jdbc:mysql://localhost:3306/digital_library?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Changed from create-drop to update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # Updated to non-deprecated dialect
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  # DevTools configuration
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
    livereload:
      enabled: true

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG